### ISSUE TITLE
Geoname ID priority search for existing records

### ISSUE THREAD

**Issue by max-arnold** [greenday2/django-cities-light#13]
Check if this one is still relevant and fix if necessary https://groups.google.com/forum/#!topic/yourlabs/aYwK3UgbAd8

**Comment by max-arnold** [comment]
TODO (опционально, сначала проверить): убрать null=True, blank=True в City.feature_code, а также awk'ом проверить (указав табуляцию как разделитель), есть ли в исходном файле города с пустым feature_code

**Comment by max-arnold** [comment]
```
awk -F'\t' '{arr[$8]++}END{for (a in arr) print a, arr[a] | "sort -nrk2"}' cities1000.txt
```

```
PPL 69409
PPLA3 27195
PPLA4 26600
PPLA2 16160
PPLA 3483
PPLX 2336
PPLC 242
PPLL 239
PPLQ 19
PPLG 14
PPLS 12
PPLF 6
PPLR 4
PPLH 4
STLMT 1
PPLW 1
```

**Comment by max-arnold** [comment]
Начал пилить в ветке https://github.com/max-arnold/django-cities-light/tree/update-by-geoname-id

**Comment by greenday2** [comment]
Closed by https://github.com/yourlabs/django-cities-light/tree/01d13a51bfff71ac765b758d51488a197a23ac9a
