### ISSUE TITLE
Customizable feature codes filter for imported cities

### ISSUE THREAD

**Issue by max-arnold** [greenday2/django-cities-light#3]
Customizable feature codes filter for imported cities (see CITY_TYPES в bak/bak2). Manually look for different sample data records behind each type (items[7]), pay extra attention to the types which are proposed for exclusion, for example PPLL and PPLX.

**Comment by greenday2** [comment]
CLosed in
https://github.com/greenday2/django-cities-light/commit/283aa64e0e5ef8b8b6b3a72e8983de69fd18e704
https://github.com/greenday2/django-cities-light/commit/2d5ddf1882f0a47fafafba3768bcdf58fa81f651
https://github.com/greenday2/django-cities-light/commit/afbf7dae514d0cbbb433aa0b9016ef5d173ca8a9
