### ISSUE TITLE
Management command to work with fixtures

### ISSUE THREAD

**Issue by max-arnold** [greenday2/django-cities-light#4]
Reusable HTTP-downloader. Separate management command called cities_light_fixtures to dump and download fixtures (+ unit tests), see django-cities-light-bak2.

Ask James if it is ok to depend on bz2 executable. It could lead to some problems on Windows. Test it and if necessary use builtin python bz2 module.

**Comment by greenday2** [comment]
Переработать Downloader под тесты, после переработки 
возможно написать следующие тесты класса Dowloader. 
- [x] Тест ф-ции `_check_source_and_dest_is_same`. 
  - Должна возвращать True если source и dest совпадают и source это файл.
  - Должна возвращать False если source и dest не совпадают и source это файл.
  - Должна возвращать False если source это не файл, а удаленный источник
  - Должна выбрасывать исключение если source это файл и он не существует.
- [x] Тест ф-ции `_get_source_prop`.
  - Должна возвращать правильные file-like объект, его дату последней модификации, его размер.
- [x] Тест ф-ции `_need_download`.
  - Должна возвращать False если дата последней модификации файла приемника (если он существует) больше либо равна дате последней модификации файла источника а их размеры совпадают. При это параметр Force=False.
  - Должна возвращать True если дата последней модификации файла приемника (если он существует) меньше даты последней модификации файла источника или их размеры не совпадают.При этом параметр Force=False.
  - Должна возвращать True если файла приемника не существует. При этом параметр Force=False.
  - Должна возвращать True если параметр Force=True.
- [x] Тест ф-ции `_download`.
  - Ф-ция должна корректно копировать данные из source в destination.
- [x] Тест ф-ции `_exists`.  
  - Должна вызвать os.path.exists и возвращать значение возвращаемое ею.
- [x] Тест ф-ции `_getmtime`.  
  - Должна вызвать os.path.getmtime и возвращать значение возвращаемое ею.
- [x] Тест ф-ции `_getsize`.  
  - Должна вызвать os.path.getsize и возвращать значение возвращаемое ею.
- [x] Тест ф-ции `download`.
  - Должна возвращать False если `_check_source_and_dest_is_same` возвращает True
  - Должна возвращать False если `_need_download` возвращает False
  - Должна возвращать True, и должен вызываться метод `_download`

**Comment by greenday2** [comment]
Тесты команды cities_light_fixtures
- [x] Тест dump. Результат: в DATA_DIR/fixtures должны быть три файла фикстур содержащие тестовые данные. (Проверить данные и сравнить что в БД)
- [x] Тест dump c указанием параметра --base-url. Результат: в каталоге указанном в base-url  должны быть три файла фикстур содержащие тестовые данные. (Проверить данные и сравнить c тем, что в БД)
- [x] Тест load. Результат: в БД должны быть загружены данные из фикстур расположенных в DATA_DIR/fixtures.
- [x] Тест load c указанием параметра --base-url. Результат: в БД должны быть загружены данные из фикстур находящихся в каталоге указанном в --base-url. В каталоге DATA_DIR/fixtures должны появиться файлы с фикстурами.
- [x] Тест load c указанием параметра --base-url и --force. В каталоге DATA_DIR/fixtures уже имеются файлы с фикстурами. Результат: в БД должны быть загружены данные из фикстур находящихся в каталоге указанном в --base-url. Файлы фикстур находящиеся в каталоге DATA_DIR/fixtures должны быть заменены на файлы из каталога указанного в параметре --base-url

**Comment by max-arnold** [comment]
Не пора ли актуализировать тикет?
