### ISSUE TITLE
Drop support for Django versions < 1.9

### ISSUE THREAD

**Issue by max-arnold** [greenday2/django-cities-light#7]
Django=>1.9 only, recreate settings and test project from scratch and drop south migrations

**Comment by greenday2** [comment]
Closed in 
https://github.com/greenday2/django-cities-light/commit/d2aee99926739ee0e1605dfdcb88b4c0b29bc3b6
https://github.com/greenday2/django-cities-light/commit/16e47de2cf8c3711dbc38ec6026e4c012b4e60f1
https://github.com/greenday2/django-cities-light/commit/a7032c1a6dd036d66a6fa0c6199d9e11eaf87f3b
https://github.com/greenday2/django-cities-light/commit/698ceb50d3c32ca30e95555e57a1b69254d6fe4f
https://github.com/greenday2/django-cities-light/commit/47837033cb9301e5e248871394dc0ffc33db21d8
https://github.com/greenday2/django-cities-light/commit/7903dd202ee32d265f1932665a40a8a44cf94c0f
https://github.com/greenday2/django-cities-light/commit/3db5243edab4a2e42ea00c95217b2109cc10e383
https://github.com/greenday2/django-cities-light/commit/7b40098719832e41bc90da3804b17595ad0d7a70
https://github.com/greenday2/django-cities-light/commit/cbd2b0cad537216a8cae96ec21e9abdbfd74e808
https://github.com/greenday2/django-cities-light/commit/94394148b78b1fe5b94d197e5dc8ea21db17eef6
https://github.com/greenday2/django-cities-light/commit/1632113183b98f1122c23032300044deec271dd7
https://github.com/greenday2/django-cities-light/commit/c53eec572c5ef13dfb5298381703ea47aef2cf6e
