### ISSUE TITLE
Improve test_project

### ISSUE THREAD

**Issue by max-arnold** [greenday2/django-cities-light#8]
See bak2 archive (requirements.txt, etc.)

**Comment by greenday2** [comment]
Solved in commits:

commit 72be744a4c301f66c9c6c73ee6691b6ea60c491e
Author: Max Arnold <arnold.maxim@gmail.com>
Date:   Mon Dec 28 13:13:45 2015 +0700

    Drop LazyProgressBar, the patch is accepted upstream as of version 3.5.2

commit 489dc0eb6c01436798778af347ce92c0bc371011
Author: Michael Gulev <greenday2.gd@gmail.com>
Date:   Fri Dec 25 18:39:52 2015 +0700

    travis: remove obsolete vendor directory from pep8 ignore list.
    
    test_project test.py: Remove obsolete in django 1.9 django.utils.unitest and use unittest.

commit c53eec572c5ef13dfb5298381703ea47aef2cf6e
Author: Max Arnold <arnold.maxim@gmail.com>
Date:   Thu Dec 10 20:56:55 2015 +0700

    fix docs

commit 1632113183b98f1122c23032300044deec271dd7
Author: Max Arnold <arnold.maxim@gmail.com>
Date:   Thu Dec 10 20:56:32 2015 +0700

    write proper docs/requirements.txt

commit 94394148b78b1fe5b94d197e5dc8ea21db17eef6
Author: Max Arnold <arnold.maxim@gmail.com>
Date:   Thu Dec 10 20:56:00 2015 +0700

    update test_project to look like it was created using django 1.9

commit cbd2b0cad537216a8cae96ec21e9abdbfd74e808
Author: Max Arnold <arnold.maxim@gmail.com>
Date:   Thu Dec 10 20:20:43 2015 +0700

    prettify test_project requirements.txt

commit 7b40098719832e41bc90da3804b17595ad0d7a70
Author: Michael Gulev <greenday2.gd@gmail.com>
Date:   Thu Dec 10 11:25:46 2015 +0700

    Change order of dependecy and up django version to 1.9 in requirements.txt

commit 3db5243edab4a2e42ea00c95217b2109cc10e383
Author: Michael Gulev <greenday2.gd@gmail.com>
Date:   Thu Dec 10 11:23:30 2015 +0700

    Remove pl, abbr translation and add ru translation. Make ready contrib to django 1.9

commit 7903dd202ee32d265f1932665a40a8a44cf94c0f
Author: Michael Gulev <greenday2.gd@gmail.com>
Date:   Tue Dec 1 22:35:01 2015 +0700

    Replace vendor/progressbar with progressbar2

commit 47837033cb9301e5e248871394dc0ffc33db21d8
Author: Michael Gulev <greenday2.gd@gmail.com>
Date:   Sun Nov 22 02:23:00 2015 +0700

    Add loggers to settings.py

commit 698ceb50d3c32ca30e95555e57a1b69254d6fe4f
Author: Michael Gulev <greenday2.gd@gmail.com>
Date:   Sun Nov 22 02:21:44 2015 +0700

    Remove South migrations.

commit a7032c1a6dd036d66a6fa0c6199d9e11eaf87f3b
Author: Michael Gulev <greenday2.gd@gmail.com>
Date:   Sun Nov 22 01:18:50 2015 +0700

    Upgrade requirements in test_project

commit 16e47de2cf8c3711dbc38ec6026e4c012b4e60f1
Author: Michael Gulev <greenday2.gd@gmail.com>
Date:   Mon Nov 9 03:50:25 2015 +0700

    New test_project on Django 1.9

commit d2aee99926739ee0e1605dfdcb88b4c0b29bc3b6
Author: Michael Gulev <greenday2.gd@gmail.com>
Date:   Mon Nov 9 01:40:58 2015 +0700

    Remove unnecessary files in test project. Add requirements.txt

Closing,

**Comment by greenday2** [comment]
Closed in 
https://github.com/greenday2/django-cities-light/commit/d2aee99926739ee0e1605dfdcb88b4c0b29bc3b6
https://github.com/greenday2/django-cities-light/commit/16e47de2cf8c3711dbc38ec6026e4c012b4e60f1
https://github.com/greenday2/django-cities-light/commit/a7032c1a6dd036d66a6fa0c6199d9e11eaf87f3b
https://github.com/greenday2/django-cities-light/commit/698ceb50d3c32ca30e95555e57a1b69254d6fe4f
https://github.com/greenday2/django-cities-light/commit/47837033cb9301e5e248871394dc0ffc33db21d8
https://github.com/greenday2/django-cities-light/commit/7903dd202ee32d265f1932665a40a8a44cf94c0f
https://github.com/greenday2/django-cities-light/commit/3db5243edab4a2e42ea00c95217b2109cc10e383
https://github.com/greenday2/django-cities-light/commit/7b40098719832e41bc90da3804b17595ad0d7a70
https://github.com/greenday2/django-cities-light/commit/cbd2b0cad537216a8cae96ec21e9abdbfd74e808
https://github.com/greenday2/django-cities-light/commit/94394148b78b1fe5b94d197e5dc8ea21db17eef6
https://github.com/greenday2/django-cities-light/commit/1632113183b98f1122c23032300044deec271dd7
https://github.com/greenday2/django-cities-light/commit/c53eec572c5ef13dfb5298381703ea47aef2cf6e

**Comment by max-arnold** [comment]
Ну всю портянку то не обязательно :)
